@url_base=http://localhost:8000/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VybmFtZTIiLCJleHAiOjE3MjEzODc4Nzh9.SrmOsbCtIyBIrP3Ltdj0HtQDf7hk1YeKq2dIOVI3f0k

### CREATE USER
POST {{url_base}}
Authorization: Bearer {{token}}

{
    "username": "username13",
    "password": "password",
    "email": "email13@example.com",
    "role_id": "52c981b8-2b64-4934-963e-a8dd754dd620"
}

### GET ALL USERS INDEX
GET {{url_base}}/index
Authorization: Bearer {{token}}

### GET ALL USERS PAGINATED
GET {{url_base}}?page=1&size=10&order_field=username&direction=desc
Authorization: Bearer {{token}}

### GET ONE USER BY ID

### GET ONE USER BY USERNAME
GET {{url_base}}/by_username/username1
Authorization: Bearer {{token}}

### UPDATE ONE USER
PUT {{url_base}}/2f431933-b76e-4ff4-853d-60b91ee0936b
Authorization: Bearer {{token}}

{
    "username": "username_new2",
    "email": "email_new2@example.com",
    "role_id": "632ab8c4-26e9-4c60-bda6-89b4eb19313b"
}

### DELETE ONE USER BY ID
DELETE {{url_base}}/986c35cc-8b27-462f-a790-951cd9d73706
Authorization: Bearer {{token}}

### DEACTIVATE ONE USER