@url_base=http://localhost:8000/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VybmFtZTIiLCJleHAiOjE3MjEzMjQ5MDh9.Ou0qCi-S5qGhbs_BzpHdEdGi6x83-Nz0j4o3n_ntg5U

### CREATE USER
POST {{url_base}}
Authorization: Bearer {{token}}

{
    "username": "username13",
    "password": "password",
    "email": "email13@example.com",
    "role_id": "52c981b8-2b64-4934-963e-a8dd754dd620"
}

### GET ALL USERS INDEX
GET {{url_base}}/index
Authorization: Bearer {{token}}

### GET ALL USERS PAGINATED
GET {{url_base}}?page=1&size=10&order_field=username&direction=desc
Authorization: Bearer {{token}}

### GET ONE USER BY ID

### GET ONE USER BY USERNAME
GET {{url_base}}/by_username/username1
Authorization: Bearer {{token}}

### UPDATE ONE USER
PUT {{url_base}}/2f431933-b76e-4ff4-853d-60b91ee0936b
Authorization: Bearer {{token}}

{
    "username": "username_new2",
    "email": "email_new2@example.com",
    "role_id": "632ab8c4-26e9-4c60-bda6-89b4eb19313b"
}

### DELETE ONE USER

### DEACTIVATE ONE USER